SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A JOIN 
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS B 
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC;

-- 다른 답안
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A JOIN 
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS B 
ON A.FOOD_TYPE = B.FOOD_TYPE 
WHERE A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC;

-- 다른 답안
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT *, RANK() OVER (PARTITION BY B.FOOD_TYPE ORDER BY B.FAVORITES DESC) AS RF
    FROM REST_INFO AS B
) AS RANKING
WHERE RANKING.RF <= 1
ORDER BY FOOD_TYPE DESC;