SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *, RANK() OVER (PARTITION BY FP.CATEGORY ORDER BY FP.PRICE DESC) AS RANKING FROM FOOD_PRODUCT AS FP
    ) AS B
WHERE B.RANKING <= 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;

-- 다른 답안
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME 
FROM FOOD_PRODUCT AS FP, (
    SELECT CATEGORY, MAX(PRICE) AS MP
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS M
WHERE FP.CATEGORY = M.CATEGORY AND FP.PRICE = M.MP
ORDER BY MAX_PRICE DESC;